import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
 import Nav from "@/components/layout/Navbar/Nav";
import Footer from "@/components/layout/footer/Footer";
import Header from "@/components/layout/header/Header";
import { Toaster } from "sonner";
import CartcontextProductProvider from "@/context/Cartcontext";
import Locationcontext from "@/context/Locationcontext";
import Idcontext from "@/context/id";
import { SessionProvider } from "next-auth/react";
import ProviderWrapper from "@/provider/ProviderWrapper";
  
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <style>
@import url('https://fonts.googleapis.com/css2?family=Alexandria:wght@100..900&family=Cairo:wght@200..1000&family=Chakra+Petch:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&family=Days+One&family=Exo+2:ital,wght@0,100..900;1,100..900&family=Exo:ital,wght@0,100..900;1,100..900&family=IBM+Plex+Sans+Arabic:wght@100;200;300;400;500;600;700&family=IBM+Plex+Sans:ital,wght@0,100..700;1,100..700&family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&family=Noto+Sans:ital,wght@0,100..900;1,100..900&family=Roboto:ital,wght@0,100..900;1,100..900&family=Space+Grotesk:wght@300..700&family=Tajawal:wght@200;300;400;500;700;800;900&display=swap');
</style>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className=" mx-auto ">


            <ProviderWrapper>


                 <Header />
                <Nav />
                {children}
                <Toaster />


                   <Footer />

             </ProviderWrapper>


             




 

   
         </div>
      </body>
    </html>
  );
}
